CREATE TABLE COVERAGE(
    GROUP_NAME VARCHAR(50),       
    CODE VARCHAR(50),   
    COUNTRY_NAME VARCHAR(100),      
    YEAR_DATA INT,               
    ANTIGEN VARCHAR(50),       
    ANTIGEN_DESCRIPTION VARCHAR(200),      
    COVERAGE_CATEGORY VARCHAR(50),
    CATEGORY_DESCRIPTION VARCHAR(200),      
    COVERAGE NUMERIC(5,2)       
	);

CREATE TABLE INCIDENCE_RATE (
    GROUP_NAME VARCHAR(50),       
    CODE VARCHAR(50),
    COUNTRY_NAME VARCHAR(100),
    YEAR_DATA INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(200),
    DENOMINATOR VARCHAR(50),
    INCIDENCE_RATE NUMERIC(12,4),
    per_1M_total_pop NUMERIC(12,4),
    per_1M_under15_pop  NUMERIC(12,4),
    per_1k_births NUMERIC(12,4)
);

CREATE TABLE REPORTED_CASES (
    GROUP_NAME VARCHAR(50),       
    CODE VARCHAR(50),
    COUNTRY_NAME VARCHAR(100),
    YEAR_DATA INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(200),
    CASES NUMERIC(12,0)
);


CREATE TABLE VACCINE_INTRODUCTION (
    ISO_3_CODE VARCHAR(50),
    COUNTRYNAME VARCHAR(100),
    WHO_REGION VARCHAR(50),
    YEAR_DATA INT,
    DESCRIPTION VARCHAR(200),
    INTRO VARCHAR(50),
    INTRO_NORM  VARCHAR(50)
);

CREATE TABLE VACCINE_SCHEDULE (
    ISO_3_CODE VARCHAR(20),
    COUNTRYNAME VARCHAR(100),
    WHO_REGION VARCHAR(50),
    YEAR_DATA  INT,
    VACCINECODE VARCHAR(20),
    VACCINE_DESCRIPTION  VARCHAR(200),
    SCHEDULEROUNDS INT,
    TARGETPOP VARCHAR(50),
    TARGETPOP_DESCRIPTION VARCHAR(200),
    GEOAREA VARCHAR(100),
    AGEADMINISTERED VARCHAR(50),
    SOURCECOMMENT VARCHAR(1000)
);

