CREATE TABLE YEARS(
	year_id SERIAL PRIMARY KEY,
	years INT UNIQUE
);

INSERT INTO YEARS(years)
SELECT DISTINCT year_data
FROM COVERAGE
ON CONFLICT (years) DO NOTHING;

INSERT INTO YEARS(years)
SELECT DISTINCT year_data
FROM INCIDENCE_RATE
ON CONFLICT (years) DO NOTHING;

INSERT INTO YEARS(years)
SELECT DISTINCT year_data
FROM REPORTED_CASES
ON CONFLICT (years) DO NOTHING;

INSERT INTO YEARS(years)
SELECT DISTINCT year_data
FROM VACCINE_INTRODUCTION
ON CONFLICT (years) DO NOTHING;

INSERT INTO YEARS(years)
SELECT DISTINCT year_data
FROM VACCINE_SCHEDULE
ON CONFLICT (years) DO NOTHING;



-- adding year_id as foreign key
ALTER TABLE COVERAGE
ADD COLUMN year_id INT REFERENCES YEARS(year_id);

ALTER TABLE INCIDENCE_RATE
ADD COLUMN year_id INT REFERENCES YEARS(year_id);

ALTER TABLE REPORTED_CASES
ADD COLUMN year_id INT REFERENCES YEARS(year_id);

ALTER TABLE VACCINE_INTRODUCTION
ADD COLUMN year_id INT REFERENCES YEARS(year_id);

ALTER TABLE VACCINE_SCHEDULE
ADD COLUMN year_id INT REFERENCES YEARS(year_id);


UPDATE COVERAGE cv
SET year_id = y.year_id
FROM YEARS y
WHERE cv.year_data = y.years;

UPDATE INCIDENCE_RATE ir
SET year_id = y.year_id
FROM YEARS y
WHERE ir.year_data = y.years;

UPDATE REPORTED_CASES rc
SET year_id = y.year_id
FROM YEARS y
WHERE rc.year_data = y.years;

UPDATE VACCINE_INTRODUCTION vi
SET year_id = y.year_id
FROM YEARS y
WHERE vi.year_data = y.years;

UPDATE VACCINE_SCHEDULE vs
SET year_id = y.year_id
FROM YEARS y
WHERE vs.year_data = y.years;


ALTER TABLE COVERAGE
DROP COLUMN year_data;

ALTER TABLE INCIDENCE_RATE
DROP COLUMN year_data;

ALTER TABLE REPORTED_CASES
DROP COLUMN year_data;

ALTER TABLE VACCINE_INTRODUCTION
DROP COLUMN year_data;

ALTER TABLE VACCINE_SCHEDULE
DROP COLUMN year_data;
